### ISSUE TITLE
Implement a mockup data generator

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#11]
Developers need data in the data model to be able to test and run the application.
# User story

```
As a developer
I need mockup data for our data model
so that i can do use case and application tests
```
# Open Task
- [x] Compile a list of 'fake data' tool, preferably with Meteor packaging
# Task
- [x] Determine the Use Case Scenarios / Development processes for 'fake data' 
  - [x] Do research and get feedback
- [x] Choose a 'fake data' tool, preferably with Meteor packaging
# Definition of done
- [x] Packages installed and basic implementation created
# Resources

Faker.js comes as an NPM module. The following packages uses Faker.js in some way.
# Packages using faker.js (to our best knowledge)
- [digilord](https://github.com/digilord/meteor-faker) | server only
- [practical meteor](https://github.com/practicalmeteor/meteor-faker) | wrapper for Fake.js , client and server , seems good
- [schema faker](https://github.com/json-schema-faker/json-schema-faker) | seems great , uses schema definitions 
- [Anticoders](https://github.com/anticoders/meteor-fake)  | good for longer texts, lacks in other features
- [gbit:faker](https://github.com/girassolbit/meteor-faker) | wrapper Fake.js , client and server, has a Blaze helper, seems better

**Comment by brylie** [comment]
@leosa83 please provide a description for this issue. If possible, add acceptance criteria, such as 'mockup data should' or 'mockup data does'. Also, please add a user story in the form of:

```
As a <user role>
I need mockup data for our data model
so that ...
```

**Comment by leosa83** [comment]
Ok will do

**Comment by leosa83** [comment]
@brylie Any feedback on this?

**Comment by brylie** [comment]
@leosa83, looks great :-)

**Comment by brylie** [comment]
We may also need to choose a Meteor package for adding the mockup data. I am not sure specifically which to use, so this would be an important part to complete the task.

**Comment by leosa83** [comment]
@brylie Seem like if we use: https://github.com/json-schema-faker/json-schema-faker
or https://github.com/Marak/faker.js , we can just generate fake data on the fly.
This issue should therefore change description and title.

**Comment by brylie** [comment]
@leosa83 also check for a Meteor package, or JS package which has Meteor support.

**Comment by brylie** [comment]
E.g. faker.js has been [packaged for Meteor](https://github.com/digilord/meteor-faker). There may be other, possibly stronger, options for generating fake data in Meteor projects, so I just want to do due diligence here.

**Comment by leosa83** [comment]
@brylie 

Faker.js comes as an NPM module. The following packages uses Faker.js in some way.

# Packages using faker.js (worth mentioning and know of)
- [digilord](https://github.com/digilord/meteor-faker) | server only
- [practical meteor](https://github.com/practicalmeteor/meteor-faker) | wrapper for Fake.js , client and server , seems good
- [schema faker](https://github.com/json-schema-faker/json-schema-faker) | seems great , uses schema definitions 
- [Anticoders](https://github.com/anticoders/meteor-fake)  | good for longer texts, lacks in other features
- [gbit:faker](https://github.com/girassolbit/meteor-faker) | wrapper Fake.js , client and server, has a Blaze helper, seems better

**Comment by leosa83** [comment]
How should we use a fake data tool @brylie? Should we have fake collections, how would we switch between a fake collection and real collections in a test environment. How do we set it up for dynamic creation of fake data so no collections are needed, how do we switch between dynamically generated data testing and other... Naturally there are many ways to use it but how do you prefer to do it? Should you be assigned this issue? No need to answer every question, just try to understand the essence of what im trying to communicate :) Thanks.

**Comment by brylie** [comment]
@leosa83 to keep our code simple, we should just add fake data to our collections. We should avoid using fake data in any production system, but would use fake data for demonstration and testing purposes.

**Comment by talltorp** [comment]
Using factories is a really nice way to describe the data that you use in tests.
But it is also a good way of generating seed data in a controlled way.

It can use libraries to fake random names, so all users emails are unique for example.

You could put this in a setup script for developers to run on first install. 

``` javascript
Factory.define('project', Projects, {
  name: function() { return Fake.sentence(); },
  rating: function() { return _.random(1, 5); }
});

_(10).times(function(n) {
  Factory.create('project');
};
```

The example is copied from here
https://github.com/Differential/meteor-boilerplate#seed-data

**Comment by leosa83** [comment]
@talltorp Sorry for not responding earlier, i thought had.. Thank you for the helpful comment :)

**Comment by leosa83** [comment]
Will be using practicalmeteor:faker

**Comment by leosa83** [comment]
Have now used practicalmeteor:faker together with  dburles:factory for a basic generator to be used in the browser console. Startup scripts to be added.
