### ISSUE TITLE
Add JSON route for Projects collection

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#13]
Create a JSON route that can be used to export documents from the Projects collection.
# User story

```
As a developer
I would like to access a JSON data endpoint for the Projects collection
so that I can integrate the data into my application
```
# Task

To complete this task, define at least two JSON routes:
- All projects
- Single project

It may be necessary to install a package to help with the JSON routing. To this end, the following packages have been mentioned:
- [simple:rest](https://atmospherejs.com/simple/rest)
- [simple:json-routes](https://atmospherejs.com/simple/json-routes)

Based on discussion, we will try the **simple:json-routes** first.
## All projects

Route: `/projects` 

The all projects route should return a JSON array of all projects, with each project document containing all project details.
## Single project

Route: `/projects/{{ _id }}`

The route should allow users to request a specific Project ID, and receive a JSON document with .Project details-
# Acceptance criteria
- [x] "All projects" route returns a JSON array of all projects
  - [x] Each project in array contains all current project details
- [x] "Single project" route returns a JSON object for one project
  - [x] Route uses ID parameter to identify project
  - [x] JSON document returns all current details about requested project

**Comment by 2ECC71** [comment]
@brylie : Is this a package we could use?
https://atmospherejs.com/simple/rest

**Comment by brylie** [comment]
Yep, that would sure give us a simple REST API! :-)

Would you like to try this task?

**Comment by 2ECC71** [comment]
I can try :)
Is there a better way to do it? Without installing a package?

**Comment by 2ECC71** [comment]
https://atmospherejs.com/simple/json-routes
Perhaps this is a better way.

**Comment by brylie** [comment]
Yep. That was the original idea, hence the issue name. Give JSON Routes a try :-)

**Comment by brylie** [comment]
I have updated the task description.
