### ISSUE TITLE
Clarify additional project requirements by creating and prioritizing issues

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#131]
There are several issues that still need definition and priority. Use the text below as the basis for creating new issues.
# Background

Last week we kick started our pilot process where we go from identifying problems to solving those and finally hacking those solutions. 
On the 6th and 7th of February we will hold the hackathon. 
Remember to signup:  http://tinyurl.com/rt-pilothack
Read more about the process: http://tinyurl.com/rt-pilothack-pdf
The outcome of that hackathon will be a couple of projects we are calling RT Projects.( #127 ).
# Purpose

The purpose of this release is to be able to support the outcome of the hackathon.
The RT Projects profile pages will include information about the history of the projects; from problem identification to solution's and prototyping on the hackathon. It will also include the key actors and potential projects owners (if any organisation has adopted the project)

Wireframes and designs for this page is beeing developed by @Davito163.
This page is the most important piece that needs to be published in this release. All other requirements make sure the UX for the rest of the site is good enough for this release.
# Instructions
- Find a child issue and self assign, and improve the issue definition 
- Help by create a child issue for one of the requirements that doesnt have one

<hr>
# Navbar
## Share button

check out #75 

<hr>
# If Big pic on page

Make sure too
- [ ] Snap points for re-sizing image based on frame size

<hr>
# Landing page
- [x] Look and feel like on mockup
  https://projects.invisionapp.com/share/HQ540EQ2S#/screens/118594700'
## 'What they say' Row
- [ ] No sidescroll as in the mockup
- [ ] Links to all articles, appearance and functionality as in the mockup
## Child issue
#141

<hr>
# About us page
- [ ] Look and feel like on mockup
  https://projects.invisionapp.com/share/HQ540EQ2S#/screens/118594703
- [ ] Develop the text @Shahin89 
  <s> \* [ ] Top picture is a moving gif image
  - [x] Create gif @Davito163 #lowprio </s>
## Child issue
#148

<hr>
# What we do Page
- [ ] Develop content @Davito163 
- [x] Implement content
  <hr>
## Child issue
#151
# Searchbar
- [x] Comment out the searchbutton

<hr>
# Type of projects present
- [ ] Only RT projects will be present for the initial release
- [x] RT projects have a different Project profile look than Other projects
  <hr>
# RT Project profile page
- [x] Related projects on project profile page **Not** in scope because it requires filters
- [x] New requirements have been set and will be documented soon
- [ ] Create basic wireframe @Davito163 
- [x] Create design @Davito163 
- [ ] Create infographics @Davito163 
## Requirements
- [x] Follow additional requirements set by wireframes and designs
## Child issues
#127

<hr>
# Footer
- [x] Copy the appearance from https://projects.invisionapp.com/share/HQ540EQ2S#/screens/118594700
  - [x] Reuse some of the html for the footer from www.refugeetech.com
- [x] 'Press inquires' link => /press
- [x] Remove 'Work Forum'
- [x] Slack Community link with slack font-awesome 
- [x] Facebook Forum link with Facebook font-awesome
## Child issue
#136

<hr>
# /press Page
- [ ] Logotypes in different formats are presented
- [ ] Picture library
  <hr>
# All below is out of scope

(<b>Keeping it here for the record<b>)
<s>
# Grouping of projects on /projects
- [ ] Grouping of projects based on
  - [ ] RT - Projects
  - [ ] Community Projects
  - [ ] Other projects
## How it should look

</s>
<s>
Analogous to this screen and the grouping there
https://projects.invisionapp.com/share/HQ540EQ2S#/screens
=> RT Projects based in Sweden
=> Community Projects based in Sweden
=> Other Projects based in Sweden
# Filter bar
- [ ] Not in scope for this release

</s>
<s>
# Blog
- [ ] Create a blog using a meteor package
- [x] New requirements have been set and will be documented soon
## Requirements
- [ ] Posts can be tagged, are shown like on mockup, not klickable (package has its own tags feature)
- [ ] All major social sharing buttons
- [ ] Searchbar searches on blogposts 
- [ ] '5 shares' => counts all shares using any of those social buttons
- [ ] Disqus comments instead of facebook plugin (because its comes with the blog package). Implement this last to give time to assess the value of going with fb plugin anyways.
- [ ] '*Source: ' functionality on pictures as in the mockup (non clickable)
### Things out of scope for this release
- Tweet/share quotes from post
## Possible packages to use
- https://github.com/meteor-blog/meteor-blog
## Child issues
#132

</s>

**Comment by leosa83** [comment]
@refugeetech/platformteam 
Please review and add to this issue and lets collaborate to work this out.

**Comment by leosa83** [comment]
@brylie How should we manage a release branch? Is it ok to strip the releasebranch from code that still exists in the develop branch?. Im wondering because some features that have been developed will not be used for 0.2 , but it seems sloppy to include code that wont be used. Or is it ok to have code lying around that wont be used in a release?

**Comment by brylie** [comment]
The release is made from the `develop` branch. In effect, the 0.2 release is a snapshot of the `develop` code at the time it is made.

**Comment by brylie** [comment]
@leosa83 please create issues for any additional features (such as those listed above) and add them to the 0.2 milestone.

**Comment by leosa83** [comment]
Ok so then it is ok to have code lying around, in a release to be published live, which is not doing anything because its not yet ready?

**Comment by leosa83** [comment]
Will do

**Comment by brylie** [comment]
We should remove any unused code, or at least comment it out to show that it is not working. This includes UI boilerplate text.

**Comment by leosa83** [comment]
Ok , lets comment it out then.

**Comment by brylie** [comment]
Alright cool. I am feeling a bit worried about the 0.2 release requirements. The 0.2 rellease seems to be slipping further away, as some considerably large features have been added to the list.

**Comment by leosa83** [comment]
Lets talk about it

**Comment by brylie** [comment]
Move these requirements into separate issues. Add a milestone to each issue (not everything needs to fit into the 0.2 release). Then, we can use the milestone page(s) to track progress:

https://github.com/refugeetech/platform/milestones/0.2

**Comment by brylie** [comment]
Large issues like this area bit hard to read, can't be granularly assigned, and duplicate the Milestone page:

https://github.com/refugeetech/platform/milestones/0.2
https://github.com/refugeetech/platform/milestones/0.3
https://github.com/refugeetech/platform/milestones/0.4
...

In general, please keep issues small with relevant details to complete the task. Follow the [guidelines described in the contributing document](https://github.com/refugeetech/platform/blob/develop/CONTRIBUTING.md#submitting-issues) including the general structure and relevant details.

**Comment by leosa83** [comment]
Will do
