### ISSUE TITLE
Publish 0.3 milestone features to a production ready branch and deploy

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#164]
We are migrating the repository for www.refugeetech.com from using a jekyll site to using the platform repository code.
# Definition of done

Features include ONLY the following AFTER having resolved all  [0.3 issues](https://github.com/refugeetech/platform/milestones/0.3)
- [ ] Landing page
- [ ] What we do route in header
  - [ ] What we do page
- [ ] About us route in footer
  - [ ] About us page
## Then do the following
- [ ] Pull into master branch
- [ ] Set up a server
- [ ] Deploy master branch server
- [ ] Change c-name of refugeetech.com to point to the new server

**Comment by leosa83** [comment]
@brylie How should we handle the fact that the releases are different from what is actually published to www.refugeetech.com ? Is the above a suitable way?

**Comment by brylie** [comment]
It seems like the front page content is nearly the same, and static sub-pages can be added easily.

One approach is to do things incrementally:
- replace the current static site with the next release version (e.g. 0.3)
- add only one or two full features to each release, e.g., the catalogue and front page
- avoid adding any boilerplate text/features to the platform, so as not to confuse visitors

Then, the platform can be continuously deployed every release, and will grow in a similar process to [Lean software development](https://en.wikipedia.org/wiki/Lean_software_development).

**Comment by leosa83** [comment]
Ok so then basically the develop branch should not have any boilerplate code and non-used active routes..

**Comment by brylie** [comment]
Yep. That way the project managers can continuously deliver releases made from `develop` or `master`, whichever you choose.

**Comment by leosa83** [comment]
Im using branch 03-production-ready in #195
