### ISSUE TITLE
Choose, add, and configure a routing solution

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#18]
In order to have URL structure in the application, we need to choose a router. The two main Meteor routing projects are:
- Iron Router
- Flow Router

Iron router has been widely adopted, but may no longer be maintained sufficiently. Flow router is newer, aims to be simpler than Iron Router, and has seen a recent upswing in adoption.
# Task
- [x] Compare Iron Router and Flow Router
- [x] Choose a router for the MVP
- [x] Add routing package to platform
- [x] Configure initial route for adding Project

**Comment by leosa83** [comment]
Regarding simplicity and rapidness of development i would go Flowrouter
But there are much less packages supporting Flowrouter

So i think we should decide based on what other packages we will need for the projects. Lets try to think ahead there. I think an issue should be opened to list all packages and frameworks the platform will use.

**Comment by brylie** [comment]
It seems like Flowrouter is a good choice. I will add this to the project ASAP.
