### ISSUE TITLE
Determine how to add and publish relational data among collections

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#19]
The Projects schema lists several relational fields:
- `contactPersonId` - individual user ID
- `teamMemberIds` - array of user IDs
- `requestIds` - array of Request IDs

We need to figure out how we will associate data with each relational field. 

E.g. how will we add new users to the team? How will we add a contact person? How will we link requests with the project?

Additionally, we may choose a package to make publishing relational data more succinct.
# Task
- [x] Determine whether Contact Persons will be Meteor.Users //Yes
- [x]  Determine whether Team Members will be Meteor.Users //Yes
## Design
- [ ] Create a UI diagram and flow-diagram depicting how to associate a ContactPersonId with a Project
- [ ] Create a UI diagram and flow-diagram depicting how to associate a TeamMemberId with a Project
- [ ] Create a UI diagram and flow-diagram depicting how to associate a Request with a Project
## Relational data publishing
- [x] Compare Meteor packages for publishing relational data
  - [lepozepo:publish-with-relations](https://github.com/Lepozepo/meteor-publish-with-relations/)
  - [reywood:publish-composite](https://github.com/englue/meteor-publish-composite/) 
  - [lepozepo:reactive-publish](https://github.com/Lepozepo/meteor-reactive-publish/)
  - [cottz:publish-relations](https://github.com/Goluis/cottz-publish-relations/)
- [x] Choose a package for publishing relational data
- [x] Install the package for publishing relational data (#87 / PR #88 )
# Related

Related issue #12
Related issue #87

**Comment by leosa83** [comment]
We could use non relation fields where possible and then refactor if needed.
The requestIDs array could be project specific and only exist within the project. Then just use namespace to refer to a specific request.

Same with Team, lets not use a relationship (have external references) it could only be an array with user accounts. Whenever someone is added to the team the project adds it. The useraccount just keeps track of the projects it is associated with.

The same logic goes for contactperson.

**Comment by leosa83** [comment]
I think this should be a Sprint 0 issue.

**Comment by brylie** [comment]
We have the same issue whether we use a relationship or store the IDs in an array within the document. Namely, how do we associate the informaiton with the Project? What does the end-user see? How do they select the related entities? Is there a list, or what type of interface element? How to preserve privacy of user data, if we use, for example, user email as primary identifier.

**Comment by brylie** [comment]
Also, the `contactPersonId` and `teamMemberIds` fields would seem to link to a User account. If this is the case, then we are already looking at a relationship type of field. 

Also, `requestIds` seem to link to separate Request entities. Either we store the requests in the project document, or we are back to the initial questions of how to allow users to link requests to projects. 

We need UI diagrams and user-flow diagrams to more fully clarify the requirements here.

**Comment by brylie** [comment]
I have added related diagramming tasks to the issue. These diagrams will help us more fully think through the requirements and communicate them with the development team.

**Comment by brylie** [comment]
Also, please understand that by 'relational field' I simply mean storing a foreign key ID in a related entity.

**Comment by leosa83** [comment]
I think we should have Teams as a collection. Each project can have several teams. Each team is an array of Meteor.User

**Comment by brylie** [comment]
The following article recommends the publish composite package:

http://justmeteor.com/blog/why-we-dont-denormalize-anymore/

**Comment by brylie** [comment]
Based on the previous article, personal experience, and the number of projects using the package, I recommend we use the **publish-composite** package.

**Comment by leosa83** [comment]
Nice

**Comment by leosa83** [comment]
I had a look at publish-composite package and i like the flexibility of it. I think we decide on going forward with this package. Do install the package and close this issue when youre able @brylie

**Comment by brylie** [comment]
I am marking this complete as we have merged related PRs.
