### ISSUE TITLE
Add problem categories to projects schema and AutoForm UI

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#20]
Projects have a `problemCategories` field. Determine the desired options list for this field, or whether this is a free-tagging field, similar to the `tags` field. 

The options will be used in the autoForm validation process, and display in the user interface.
# Task
## Schema
- [x] `problemCategories` field is defined in `ProjectsSchema`
- [x] `problemCategories` has the following for `allowedValues`
  - [x] `social`
  - [x] `bureaucracy`
  - [x] `housing`
  - [x] `education`
  - [x] `language`
  - [x] `employment`
  - [x] `coordination`
## AutoForm
- [x] _Add Project_ form displays `problemCategories` field
- [x] `problemCategories` field displays as checkboxes (multi-select)
- [x] Checkbox labels have human readable text (e.g. capitalization)
- [x] Checkbox values match machine format from schema

**Comment by leosa83** [comment]
Social,Bureaucracy,Housing,Education & Languages,Employment,Coordination,Healthcare

**Comment by leosa83** [comment]
Should this be documented somehow? We got those categories from our problem identification workshop and report. 
[problem_identification_workshop_report.pdf](https://github.com/refugeetech/platform/files/49838/problem_identification_workshop_report.pdf)

**Comment by brylie** [comment]
Yep. We need them in the project documentation. Please add them to the repository, in markdown or some other plain text format. I will work from the list in this issue.
