### ISSUE TITLE
Create a new API using a meteor API package

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#205]
# About

There is no need to reinvent the wheel. Some people prefer to adhere to the JSON API 1.0 Specificaton but for an MVP i believe following the JSend format.
# List of potential packages
- [Restivus](https://github.com/kahmali/meteor-restivus)
  - Follow the JSend format
- [simple:rest](https://github.com/stubailo/meteor-rest)
  -Some more research needed into this one

I believe the easiest choice would be Restivus.
# Todos
- [ ] Step 1
- [x]   Step 1.0
- [x]     Install users package (to handle api users)
- [x]     Install roles package 
- [x]     Install the restivus api package
- [x]     Configure the package
- [x]     Test the installation
- [ ] Step 1.1
- [x] Install npm module [apidoc](http://apidocjs.com/) to autogenerate api documentation pages from javadoc annotations
- [ ] Configure apidoc using the apidoc.json file :
