### ISSUE TITLE
Implement currentStage field options

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#21]
Projects have a `currentStage` field. Determine the desired options for this field.

The options will be used in the autoForm validation process, and display in the user interface.
# Task
- [x] Determine initial project stage options
## Schema
- [x] `currentStage` field is added to Projects collection schema
- [x] `currentStage` field schema has an `allowedValues` property
  - [x] `allowedValues` accepts the camelCase version of each _project stage_
## AutoForm
- [x] `currentStage` field is added to _Add Project_ field
- [x] `currentStage` field is rendered as a drop-down
- [x] `currentStage` drop-down contains human-readable versions of allowed values
  - [x] Each primary letter is capitalized
- [x] `currentStage` dropdown values correspond with the allowed values defined in Projects collection schema
# Related

Related issue #12

**Comment by 2ECC71** [comment]
I'll take this.
A quick google search for "project management phases" gives me 4-5 phases, roughly:
1. Initiation
2. Planning
3. Implementation/Execution
4. Operation/Monitoring
5. Closing

Does that seem reasonable? 
EDIT, realised we will have all sorts of projects.

**Comment by brylie** [comment]
@loxtank these stages look good. Would you like to add the `projectStatus` field to the `Projects` schema, and configure the options as `allowedValues`?

**Comment by brylie** [comment]
@loxtank I have updated the task description. Will you please carry this task forward?

**Comment by 2ECC71** [comment]
Yep. I'll do it.
