### ISSUE TITLE
Create ProblemCategories collection and management UI

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#22]
Problem categories can be managed through the User Interface, if they have a collection as a backend. If the project categories may change over time, and it is not desirable to hard-code them into the system, add a  `ProblemCategories` collection. This will then necessitate a relationship between Problem Categories and any related entities, such as Projects.
# Task

Create a ProblemCategories collection, schema, and management UI.
# Acceptance Criteria
- [x] `ProblemCategories` or `IssueCategories` collection is added to project
- [x] `ProblemCategoriesSchema` is created and contains relevant fields (aside from `_id`)
  - [x] `name` field
- [x] `ProblemCategoriesSchema` is attached to `ProblemCategories` collection
- [x] `ProblemCategories` allow rules created
  - [x] `insert` always true, for now
- [x] `problemCategories` template exists
  - [x] shows list of problem categories
- [x] `newProblemCategory` template exists
  - [x] contains AutoForm with relevant fields
# File structure

This project is using a feature module organization pattern. Please use the following, or similar, file structture:
- / (project root)
  - problemCategories/
    - both/
      - collections/
        - collection.js
        - schema.js
        - permissions.js
    - client/
      - templates/
        - templateName.html
        - templateName.js
    - server/
      - methods.js
      - publications.js
# Reference

The following code example is nearly exactly what this task requires (although in a different folder structure):
- https://github.com/GeriLife/wellbeing/tree/master/client/views/activityTypes

**Comment by leosa83** [comment]
Agree.

**Comment by leosa83** [comment]
Is the project currently using the feature module organization pattern for Projects collection? @brylie

**Comment by leosa83** [comment]
@brylie What naming convention are we using for the new Mongo.Collections('name') : camelcase, underscore or something else? Ive read its best practice to only use lowercase letters..

**Comment by brylie** [comment]
Camel case for collection names. The collection variable starts with an upper case, while the collection name (in parenthesis) is camelCase.

**Comment by leosa83** [comment]
Ok

**Comment by leosa83** [comment]
There seem to have been an error: we have hardcoded the problemcategories in #20 in the project s schema. Shouldnt we have used a relationship instead...? @brylie But i recall that you said somewhere that we should hardcode.. Are we then going to close this issue and not use problemCategories schema. Or should we complete this issue and just go with hardcoded anyways initially..?

**Comment by brylie** [comment]
@leosa83 for the MVP we might benefit by simply hard-coding the problem categories and adding translation strings. 

If we put the categories into a colleciton, we have to figure out how to allow edits, removal, etc while ensuring that projects maintain relationships with categories. We also need to add translation UI to the categories management UI.

**Comment by leosa83** [comment]
@brylie I think you are right, im having some issues doing this for the Tags schema. Then for the MVP we will hardcode. I will remove the projectCategories schema from the project.

**Comment by brylie** [comment]
OK, cool. Should we assign this task to a later milestone, or close it?

**Comment by leosa83** [comment]
I think we can close it for now. Will close it with a merge commit that removes the folder structure.
