### ISSUE TITLE
Determine character limit for projectSummary field

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#25]
The Projects schema contains a [`projectSummary` field](https://github.com/refugeetech/platform/blob/develop/lib/collections/projects/schema.js#L11-L14). It may be desirable to enforce a character limit on this field, so that it falls within a certain limit. Add a character limit via the ProjectsSchema.
# Task
- [x] Clone the repository locally
- [x] Create a new feature branch based on develop
- [x] Locate the [`projectSummary` field in the Projects collection schema](https://github.com/refugeetech/platform/blob/develop/lib/collections/projects/schema.js#L11-L14)
- [x] Add a `max` attribute to the `projectSummary` field object
- [x] Benchmark and determine the size of 'max'
- [x] Set the size of 'max'
- [x] Commit your changes and push to Github
- [x] Open a pull request to have your changes reviewed before being merged into develop
# Reference
- aldeed:simple-schema [min/max documentation](https://github.com/aldeed/meteor-simple-schema#minmax)

**Comment by leosa83** [comment]
It should be tweet sized: 140

**Comment by brylie** [comment]
@leosa83 I have updated the task description to include specific steps and links to relevant information.

**Comment by leosa83** [comment]
@brylie Thank you for the detailed steps!

**Comment by leosa83** [comment]
Updated the description. projectShort is 140 sized.

**Comment by 2ECC71** [comment]
I'll take this

**Comment by 2ECC71** [comment]
@brylie @leosa83 What is a suitable length for the summary? 500 chars seems to fill the field at it's default size. Is the summary just a summary of the project description? Than maybe 500 chars is enough?

**Comment by leosa83** [comment]
Yes i think its enough. Thanks!
