### ISSUE TITLE
Add targetPlatforms field options to schema and UI

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#28]
Projects have a `targetPlatforms` field. The options will be used in the autoForm validation process, and display in the user interface.
# Target platform options

The following options have been identified for the Target Platforms:
- Web, 
- iOS, 
- Android,
- Windows Phone, 
# Task
- [x] Determine the desired options for this field.
- [x] Add the target platform allowed values to the Projects schema
- [x] Populate the 'Target Platform' select list with corresponding key/value pairs
# Related

Related issue #12

**Comment by leosa83** [comment]
Web, Ios, Android,Windows mobile, PC, Mac, Linux, Ubuntu
(maybe some functionality to only show the 4 most common as default, then load more or something)

**Comment by brylie** [comment]
OK, the 'show the most common as default' may be non trivial. However, we can easily display a list of options, based on your reply above.

**Comment by leosa83** [comment]
Lets just have list with only Web, Android, iOS, Windows Mobile

**Comment by leosa83** [comment]
Updated the requirements.

**Comment by yboulkaid** [comment]
PR for this : #35
