### ISSUE TITLE
Determine data structure for Project `address` field

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#29]
The Projects schema contains an `address` field. Determine the data structure for `postalAddress` field, and how to dynamically collect the information.
# Task
- [x] Research international postal address standards
- [x] Research address packages for Meteor.js
- [x] Determine the required fields for a postal address object
- [x] Determine conditional logic for regional postal address variations
- [x] Determine how to validate address fields
- [x] Document answers to all tasks in this issue
- [x] Rename `address` field to `postalAddress`
- [x] Add sub-fields to the `postalAddress` object
# Related
#12

MVP implementation is #32

**Comment by leosa83** [comment]
the adress field should be and adress object in a universal format

**Comment by brylie** [comment]
OK, what format? What fields does the format contain? How are addresses encoded for different locales?

**Comment by brylie** [comment]
This is not a trivial task, so I am moving it to Sprint 1. If we simply display a text field for `postalAddress`, we can collect the information (albeit in an unstructured form). If we need structured data, we have to research and plan this task a bit more.

**Comment by leosa83** [comment]
There should be several commonly used formats for the data structure that includes locales. We investigate this and then only use those fields we need. So im still thinking it is trivial though.

**Comment by leosa83** [comment]
Ok i saw now that you had already created the tasks for this.

**Comment by brylie** [comment]
@leosa83 would you like to take this task?

**Comment by talltorp** [comment]
The postal address could have a similar structure to the one google address autocomplete returns.
https://developers.google.com/maps/documentation/geocoding/intro#Types

I have implemented a version of the autocomplete in this (not yet released) rails app.
[Try it](http://insamlingslistan.herokuapp.com/) | [Code on GitHub](https://github.com/talltorp/insamlingslistan)
1. Click the button
2. Write something in the field "Var sker insamlingen?"

This saves the complete address string in a structured string.

Might this be of use?

**Comment by leosa83** [comment]
Thanks @talltorp, will look it up. Yes ill take this @brylie

**Comment by leosa83** [comment]
What if we begin with just country and postal code as fields in Project, and later go for a structured adress object? I think this will save up som time spent on really low prio stuff.
