### ISSUE TITLE
Design Project links field display and data structure

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#30]
The Projects schema has a `links` field. Determine the data structure for links, and how the data should display. E.g. are there pre-set link types? Should the link be an object with type/link keys and corresponding values for link type and the URI?
# Task
## Links field
- [x] Project schema contains `links` field
- [x] Links field type is 'array of objects' `[Object]`
- [x] Links field contains sub-fields
  - [x] `name` (type: string)
  - [x] `type` (type: string)
  - [x] `uri` (type: string)
    - [x] `uri` field uses URI RegEx for validation
## Display links in project cards
- [x] `individualProject` template updated to display `each links` field value
  - {{# each links }} ... {{/ each }}
- [x] `individualProject` template updated to display `each socialMedia` field value
  - {{# each socialMedia }} ... {{/ each }}

**Comment by leosa83** [comment]
link:{title: 'string', adress:'adress', description:'longstring' , hover:'hover text'}

Not sure if we will need description.. The usecase is for projects to be able to promote stuff, to have a list of links.

**Comment by leosa83** [comment]
Shouldnt we also have social links, that are predifined types. I.e facebook, linkedin, etc ?

**Comment by leosa83** [comment]
Something like the following will do where we keep track of a predefined set of linktypes. the linklist type is for having any type of link. the social for social etc.:
links { social: {facebook: 'uri', linkedin:'uri', othersocial: 'uri' }, linklist: [{name: 'string', uri:'uri', description:'string' , hover:'string'}]. Other types could be added: partners, etc. But at the moment we really onle need social and linklist i think.

**Comment by brylie** [comment]
@leosa83 would you take this task?

**Comment by leosa83** [comment]
will do

**Comment by leosa83** [comment]
I find it easier to loop over an array of objects rather than over an objects fields therefore ill change the datastructure, in the description, of socialMedia to be the same as that of links field.

**Comment by leosa83** [comment]
Removed socialMedia as a spearate field and added type field to links
