### ISSUE TITLE
Implement fields for country and city into Project schema

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#32]
# Open Task
- [ ] Determine how to validate postal Address field
- [ ] Document the method/tool for validation
# Task
- [x] Rename `address` field to `postalAddress`
  - [x] Set `postalAddress` field type to `Object`
- [x] Add sub-fields to the `postalAddress` object
  - [x] `country` - type: String
  - [x] `city` - type: String
- [x] Add `postalAddress` field to [Add Project form](https://github.com/refugeetech/platform/blob/develop/projects/add/client/addProject.html#L3-L30)
- [ ] Add validation of city and country
# Reference

Refer to the [aldeed:simple-schema](https://github.com/aldeed/meteor-simple-schema) documentation for examples of object fields with sub-fields:
- [field types](https://github.com/aldeed/meteor-simple-schema#type)
- [sub-fields](https://github.com/aldeed/meteor-simple-schema#schema-keys)

E.g. of an object field with sub keys:

``` js
MySchema = new SimpleSchema({
    "postalAddress.country": {
        type: String
    },
    "postalAddress.city": {
        type: String
    }
});
```
# Related

This is an MVP implementation of #29
## Meteor packages
- [AutoForm Googleplace](https://atmospherejs.com/lukemadera/autoform-googleplace) -- adds an input widget to autoforms that can populate city and country (and more) based on a Googleplaces search
- [Country ISO Info](https://atmospherejs.com/smeevil/country-iso-info) -- this package contains a lot of information at the country, region, and continent level, and may be useful for managing our list of country names/abbreviations

**Comment by Angamanga** [comment]
I can also help out with this one, am researching something similar for another project!

**Comment by leosa83** [comment]
Nice! Have you checked out #29 ?

**Comment by leosa83** [comment]
@Angamanga Because it might be what you really are investigating for the other project as this issue is pretty trivial.

**Comment by leosa83** [comment]
Ah ok now i see , you are talking about the Open Tasks, they are not so trivial.  Sorry forgot about those.

**Comment by Angamanga** [comment]
Yeah, I did, but #29 definitely is useful :)

**Comment by brylie** [comment]
@Angamanga will you take this task? It simply involves creating a schema for the `postalAddress` field, with the data type `Object`. The `postalAddress` field has two sub-fields, `country` and `postalCode`, which are both type `String`.

Refer to the [aldeed:simple-schema](https://github.com/aldeed/meteor-simple-schema) documentation for examples of object fields with sub-fields:
- [field types](https://github.com/aldeed/meteor-simple-schema#type)
- [sub-fields](https://github.com/aldeed/meteor-simple-schema#schema-keys)

E.g. of an object field with sub keys:

``` js
MySchema = new SimpleSchema({
    "postalAddress.country": {
        type: String
    },
    "postalAddress.postCode": {
        type: String
    }
});
```

**Comment by Angamanga** [comment]
Yep!

**Comment by Angamanga** [comment]
A question, do we want city or postCode? Or both? In the task-description it says city and @brylie you wrote postCode above in your comment. I just want to double-check. I also noticed in the schema that some of the fields are expecting the input values via arrays and some don't ([String] for some and just String for others), what determines that? Are the arrays for fields where many separate values are expected?

**Comment by leosa83** [comment]
@Angamanga Check the API of bring; does it need a city code? If it does we have citycode aswell and not if it doesnt. If you seem to need much time to investigate this than just use city code instead.

Regarding the schema - i was iterating on that today and was going to post but i lost all of my work. I think its yes to your question. Where one would expect one to many/many to many relationship there should be an array with the proper type.

**Comment by Angamanga** [comment]
@leosa83 The bring api only need a postCode and is very simple to use, I managed to use it today without much work. But it only works for a few countries. Which countries do we expect projects from? Only Sweden? Then the Bring-api is an option, but if we want a more country-independent validator, we need something else (and that is probably a good idea if we want the platform to be of use for other interested countries as well :)). @brylie gave me this link today: https://github.com/lukemadera/meteor-autoform-googleplace, which only need city and country, and it seems a bit more suitable but I haven't had time to try it yet...

Oh, how terrible to loose your work, very frustrating:(. Hope you manage to sort it out!

**Comment by leosa83** [comment]
@Angamanga Ok i see, then municipalities would be cities right? Like Järfälla , Sweden : but that would give a lot of possible post codes.. Maybe we dont need that specific information at the moment since we are probably not sending anything to those involed. When we need it we could refactor or just have a latent postCode field in the schema that is not used..

Thanks, no worries :) It happens once in a year so now i look forward to not having to worry about that for another year :D

**Comment by Angamanga** [comment]
Yes, exactly, so using Bring would make the locations be a bit weird in the larger city-areas where there are a lot of smaller municipalities, like Stockholm. And it might be wierd in larger municipalities with lots of smaller towns too when I think about it. I think city is enough, as long as we validate it in some way so we don't get lots of different spellings etc. I'll check googleplace out a bit more during the week!

**Comment by brylie** [comment]
@Angamanga great! It looks like you are sorted. Using `country` and `city` is good for now, and is probably simpler in some ways than the `postalCode` field.

I have updated the issue description with reference and example code from my previous comment.

**Comment by Angamanga** [comment]
Ok, have pushed the new schema and added the form but no validation yet. I have a question to @brylie, where should I put the validation function? Directly in the schema.js file, in the same directory or is it better with a utils directory with that kind of stuff?
