### ISSUE TITLE
Compile a list of existing tech projects targeting the integration process

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#33]
# Task
- [ ] Research existing projects using other listings and google
  ## Sources
  
  source#1(https://techfugees.slack.com/archives/meta-coordination/p1452167145000006))
  http://simonbjohnson.github.io/europe-refugees-16-3w/
  based on: https://docs.google.com/spreadsheets/d/1C9fmpzb3VhoGOsCnRAnhbXZNkKd3sVZIN0Ha1VOBQjk/edit#gid=1142452757
- [ ] Create a google form based on the projects schema
- [ ] Input all existing projects using the google form
- [ ] Export the result to csv
- [ ] Create a script to load the csv into mongoDB during development
# Extended Task
- [ ] Publicize the form
# Contents of the webform: Apply to Refugee Tech project hub
## Project Details

Name
Startup date
### Social

Website
Facebook
Github
Other
### Contact person

Name
Email
Phone
### Origin

Country
City
### Value model

Problem description: what problem are you trying to solve
Problem category: how would you categorize this problem
Who are the target users
Who are the problem owners

**Comment by Angamanga** [comment]
I'm in!

**Comment by brylie** [comment]
@leosa83 status update?

**Comment by leosa83** [comment]
@angamanga is doing this
Den 23 dec 2015 09:26 skrev "Brylie Christopher Oxley" <
notifications@github.com>:

**Comment by brylie** [comment]
OK, be sure to keep the Assignee field accurate, so that we know who is working on what.

**Comment by leosa83** [comment]
Will do

**Comment by Angamanga** [comment]
@leosa83 A form is found here: https://docs.google.com/forms/d/18Ho3xTLrUkBv3N5F3Coewybj-fVdXYLWtVk5fMEd1pM/viewform 

I am wondering two things: 1. do we already have specific tags we want to use? 2. I got a list of projects from you in december, are they ok to add?

**Comment by Angamanga** [comment]
@leosa83 @brylie One more question, in the schema.js file there are a Teams-feature that is commented out. Should that info still be included in the form?

**Comment by brylie** [comment]
It is fine to include it in the form. We need to develop the teams feature in the software, but there is no reason not to collect the information from project coordinators via a webform.

**Comment by miladf** [comment]
Here's something we started with some time ago:
https://docs.google.com/spreadsheets/d/1TIwiec7jSqyUqhwMWU5YNKyaE9sIRmcJ3qOAHBZ0CeU/edit?usp=sharing

**Comment by leosa83** [comment]
Nice @miladf had forgotten about that one :+1:  We could use that for ourselves, its nice to have it in spreadsheet form.
But now im thinking that we could set up a cloud 9 instance with the sole purpose of adding projects to the database. We could then export it with some package. 
This also reminds mee that wee need an edit functionality for projects.
@brylie Could you set up an issue for editing projects information?
