### ISSUE TITLE
Update landing page with project details

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#49]
The `landing` template does not have any content. Add some basic text and page elements to describe the RefugeeTech Platform.
# Task
- [x] Choose a starter template from [Bootstrap Zero](http://www.bootstrapzero.com/)
  - [x] Consider using [Landing Zero](http://www.bootstrapzero.com/bootstrap-template/landing-zero-free-bootstrap-theme)
- [x] View source code of starter template.
- [x] Add CSS files under `landing/client/style`
- [x] Add image files to `/public/images`
- [ ] Copy theme body into `landing/client/landing.html`
- [x] Replace placeholder text with text that is relevant to RefugeeTech
- [x] Remove any unused page elements
# Additional resources
- [Bootstrap cover photo example](http://www.bootply.com/5NTV3WbKmQ)

**Comment by brylie** [comment]
@loxtank, would you consider taking this task?

**Comment by 2ECC71** [comment]
sure!

**Comment by brylie** [comment]
Thanks :-)

**Comment by brylie** [comment]
Be sure to work in a feature branch, by branching from `develop`

**Comment by 2ECC71** [comment]
yup

**Comment by brylie** [comment]
I just merged the Projects related views. Please include a link to `/projects` in your landing page navigation menu. Everything else about the landing page is stand-alone for the timebeing.

**Comment by 2ECC71** [comment]
Will this actually be used for anything other then testing? 
Should the project link open a new page or be a part of the "one page design" of landing zero?

**Comment by brylie** [comment]
The _Projects_ link should open the `/projects` page in the same window. Our application uses a routing layer, so has multiple paths and pages.
