### ISSUE TITLE
Request that all organization members make membership public

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#60]
To demonstrate a growing community around our project, it would be useful to show the public who is involved in our project. To this end, each team member can make their membership public. 
# Task
- [ ] Get as many team members to make their membership public
  - [ ] Platform team (8 members)
  - [ ] Refugeetech.com team (6 members)
  - [ ] All current members (11 members)

**Comment by brylie** [comment]
@refugeetech/platformteam please make your organization membership public by visiting the following page:
https://github.com/orgs/refugeetech/people

Click the lock icon next to your name, and choose "Public"

**Comment by brylie** [comment]
@refugeetech/refugeetech-com please make your organization membership public by visiting the following page:
https://github.com/orgs/refugeetech/people

Click the lock icon next to your name, and choose "Public"

**Comment by leosa83** [comment]
Not everyone are active, so at the moment i would only request that @davidpaulsson does this for both /platform and /refugeetech.github.io Thanks!

**Comment by leosa83** [comment]
@refugeetech/platformteam 
@refugeetech/design 
@refugeetech/develop 

Please make your membership public
