### ISSUE TITLE
Create wireframe for Project Entry Form

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#7]
Projects will be submitted via an HTML form. In order to develop this form, we need a clear picture of what components it will have. 
# User stories

```
As a developer
I would like to see a wireframe for the feature I am developing
so that I have a clear, visual understanding of my working goal
```

```
As an end-user
I would like to see a user-centric design process
so that I know the software was designed to meet human needs and capabilities
```

```
As a designer
I would like to see multiple distinct wireframes for a given feature
so that I know the possible design space was explored well
```

```
As a project owner
I would like for people to create accounts on the projecthub
so that when they create projects the information needed for the application is reused for the project profile.
```
# Task

Produce at least two simple, low-fidelity [wireframes](https://en.wikipedia.org/wiki/Website_wireframe) depicting the 'Add Project' form, including all fields. The wireframes should be distinct, to demonstrate multiple design possibilities.
# Definition of Done
- [ ] Wireframes should be in a standard format such as SVG or PNG
- [ ] Wireframes should use color only for annotation/emphasis
- [ ] Wireframes should depict all fields
  - [ ] Optionally include field requirements
# Resources

Example wireframe
![Wikipedia profile wireframe](https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Profilewireframe.png/130px-Profilewireframe.png)
