### ISSUE TITLE
Create issues based on the mockup

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#70]
We need to create project issues based on this mockup, in order to prioritize and track our efforts.
# Mockup

![rt_hub_menu](https://cloud.githubusercontent.com/assets/710548/12224637/ae3caf84-b7f6-11e5-9170-95ad6b224efb.png)
https://projects.invisionapp.com/share/J353G8DCW#/screens/118855239
# Definition of Done
- [x] All aspects of the projecthub have been issued from these designs
## Child issues

Specifically, the following issues have been opened related to completing this task:
### Navigation menu
- [x] #71 - Add navigation menu to default layout
- [x] #67 - Navbar shrink state
### Translation/internationalization
- [ ] #73 - Choose and add internationalization (i18n) framework
- [ ] #72 - Add language select to navigation menu
- [ ] #109 - Language select, drop-down on hover
### Share content
- [ ] #75 - Add "Share overlay" feature and link to front page
- [ ] #76 - Add social media links to "share overlay"
### Search projects
- [x] #77 - Add search feature for Projects collection
- [x] #78 - Add search feature to front page
### Filter bar
- [ ] #68 - Create Projects collection filtering functions 
- [ ] #106 - Filter bar enhancements
### Projects profile page
- [x] #80 - Create issues based on the Project profile page 
## Reviewing

@brylie @mark-mcevoy reviews this description/issue increasing list of requirements and created issues that have been associated.

**Comment by leosa83** [comment]
@refugeetech/platformteam 

Have a look at the description of this issue. There is much todo still. It would  give us structured requirements  to create the issues needed for effective collaboration. We need to collaborate on this.

@miladf 

Have a look and give any feedback necessary based on your standpoint

**Comment by brylie** [comment]
I recommend using relative values for layout, such as `em` or `rem`. Pixel based values should be used only where required, on elements such as borders. Specifically, 55px and 75px are rather arbitrary, and could easily be expressed in relative values: 
* 75px: 4.5em
* 55px: 3.5em

**Comment by leosa83** [comment]
Thank you @brylie for reviewing and creating issues!

**Comment by brylie** [comment]
Marking this as complete, as most of the prominent issues have been added to backlog. We can continue to manage our backlog as time progresses.
