### ISSUE TITLE
Implement MVP Project Profile feature

### ISSUE THREAD

**Issue by leosa83** [refugeetech/platform#81]
# Description

In order for users to view details about a given project, we need to plan/design a Project profile feature. 
## MVP

The MVP feature will have the following capabilities:
- Project title
- Project description
- Project 'metadata'
  - Launch date (year format)
  - Category
  - Location (City)
  - Target platform
  - Social media links
  - Website link
## MVP Enhancements

Subsequent iterations of the Project Profile feature will have the following capabilities:
- [x] Project photos (based on Project Media feature #83)
- [ ] Share link (based on Share Project feature #84)
- [x] Progress bar (based on Project Progress feature #85)
# Definition of done
## Design
- [x] Wireframe exists for Project view
  - [ ] Wireframe is monochrome (optionally one additional color to emphasize annotations)
  - [ ] Wireframe is annotated with each sub-component
  - [ ]  Wireframe indicates which sub-components are part of MVP
- [ ] Static mock-up exists showing only Project profile design (e.g. no extra page elements such as footers, page sections from different features, etc)
## Code structure
- [x] Folder/file structure exists for project feature
  - [x] folder/file structure follows a Meteor package based architecture
## Route #89
- [x] Route exists for viewing individual project
- [x] Route takes a `projectID` argument
- [x] Route renders `singleProject` template (component)
## Publication #89
- [x] `singleProject` publication exists
- [x] `singleProject` publication takes `projectId` argument
- [x] `singleProject` publication returns a database cursor
  - [x] database cursor receives project ID in `find()` method: `Projects.find(projectId)`
## Project profile component #89
- [x] `projectProfile` template exists
  - [x] `projectProfile` template gets Project ID from route in `onCreated` lifecycle callback
  - [x] `projectProfile` template subscribes to `singleProject` publication
    - [x] `projectId` is passed in to `singleProject` subscription

_Note:_ For the time being, the `projectProfile` component can also render all project data.
- [x] `projectProfile` renders all MVP fields
### Page header  #89
- [x] Project name is rendered as page header
  - [x] Project name markup contains Bootstrap `page-header` class (or equivalent)
### Project details  #89

The following fields render in a project details page element.
- [x] Launch date (year format)
- [x] Category
- [x] Location (City)
- [x] Target platform
- [x] Social media links
- [x] Website link
## HTML/CSS
- [x] UI Components are styled using Bootstrap semantics
  - [ ] Bootstrap classes are extended where needed, by inheritance
- [x] UI Components match color/design of styleguide
# Parent issue
#80
# Child issues
#89
# Design

![rt_hub_wf_009_1_articlepage_v4_dt](https://cloud.githubusercontent.com/assets/710548/12272331/40572aa6-b960-11e5-85b7-cba8155ef123.png)

**Comment by brylie** [comment]
@leosa83 this issue is very vague. It might be better to focus development one specific feature at a time. Each feature branch adds relevant templates and logic, so we don't really need to pre-populate the project with empty files.

**Comment by virre** [comment]
In the branch origin/feature-issue81-frontend is a inital sketch of a design for the profile page, some details is not yet explained and some details need to be changed, but all visual elements are in somekind of place to match the design image here. Functionalities are also missing.

**Comment by leosa83** [comment]
Evrything for requirements 0.2 has been implemented: will close this issue for now.
