### ISSUE TITLE
Create basic styleguide

### ISSUE THREAD

**Issue by brylie** [refugeetech/platform#9]
Project designers need a designated style guide on which to base design choices. This styleguide will be expanded in subsequent sprints.
# User story

```
As a designer
I would like a style guide
so that I can quickly understand and follow design decisions
```
# Task
- [ ] Create a basic styleguide
# Definition of done
- [ ] Styleguide should include a color palette
  - [ ] include primary color (hex format)
  - [ ] include secondary color (hex format)
- [ ] Styleguide should include suggestion(s) on typography
  - [ ] Open-source web font selection
- [ ] Include tone of website content (e.g. casual, formal, urgent, etc)

**Comment by leosa83** [comment]
This styleguide should already exist based on our UX leads designs @davidtobar.

**Comment by leosa83** [comment]
One could just use the current style in refugeetech.com until we have a formal style guide.

**Comment by leosa83** [comment]
@modsmoss @virre @josefcarlsson WIll you be neeing a styleguide or are the mockups enough for you to go on?

**Comment by modsmoss** [comment]
I think we can do without for now but it would definitely help in future iterations. I think we should start already by gathering code snippets together with descriptions and images of the appearance. That way you can just go and grab a snippet when adding an element later on, and keep it consistent throughout the project. Does anyone know a good tool for this? @virre @josefcarlsson @leosa83

**Comment by leosa83** [comment]
Ok great @modsmoss , i dont know about any tool for that. What we could do without a tool is to modularize using templates and potentially having a folder called snippets where snippets are documented and maybe have a route /snippets for development purposes.
